### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory: '/userdata/system/configs/drastic/drastic'

### ISSUE THREAD

**Issue by lolkobr4** [rg35xx-cfw/rg35xx-cfw.github.io#169]
Hello,

after flashing and setting up an es_systems.cfg file and trying to start Drastic, i get the following error log:

```
killall: evmapy: no process killed
2024-03-05 11:22:43,131 ERROR (emulatorlauncher:603):<module> configgen exception: 
Traceback (most recent call last):
  File "/usr/bin/emulatorlauncher", line 601, in <module>
    exitcode = main(args, maxnbplayers)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/emulatorlauncher", line 99, in main
    return start_rom(args, maxnbplayers, args.rom, args.rom)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/emulatorlauncher", line 263, in start_rom
    cmd = generator.generate(system, rom, playersControllers, guns, wheels, gameResolution)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/configgen/generators/drastic/drasticGenerator.py", line 28, in generate
    shutil.copyfile("/usr/bin/drastic", drastic_bin)
  File "/usr/lib/python3.11/shutil.py", line 258, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: '/userdata/system/configs/drastic/drastic'
```

The directory "/userdata/system/configs/drastic/drastic" is in fact a directory. I have not found a solution for that. Been trying to flash it 3 times by now, in case I overlooked something, yet no change in the error. Havent found anything related to that on the internet either...

![grafik](https://github.com/rg35xx-cfw/rg35xx-cfw.github.io/assets/58613298/624d12c0-d229-4fc2-b589-101b82c0358d)

Trying to start the Emulator doesnt work and will crash upon trying to launch.

es_system_nds.cfg (located in /userdata/system/configs/emulationstation) content:
```
<?xml version="1.0"?>
<systemList>
<system>
        <fullname>Nintendo DS</fullname>
        <name>nds</name>
        <manufacturer>Nintendo</manufacturer>
        <release>2004</release>
        <hardware>portable</hardware>
        <path>/userdata/roms/nds</path>
        <extension>.nds .bin .zip .7z</extension>
        <command>emulatorlauncher %CONTROLLERSCONFIG% -system %SYSTEM% -rom %ROM% -gameinfoxml %GAMEINFOXML% -systemname %SYSTEMNAME%</command>
        <platform>nds</platform>
        <theme>nds</theme>
        <emulators>
            <emulator name="drastic">
                <cores>
                    <core incompatible_extensions=".7z">drastic</core>
                </cores>
            </emulator>
        </emulators>
</system>
</systemList>
```

Maybe someone on here has a solution for that.

Cheers!

**Comment by lolkobr4** [comment]
Changing the config file to this:
```
<?xml version="1.0"?>
<systemList>
<system>
        <fullname>Nintendo DS</fullname>
        <name>nds</name>
        <manufacturer>Nintendo</manufacturer>
        <release>2004</release>
        <hardware>portable</hardware>
        <path>/userdata/roms/nds</path>
        <extension>.nds .bin .zip .7z</extension>
        <command>/userdata/system/.simplemenu/launchers/drastic_sa %ROM%</command>
        <platform>nds</platform>
        <theme>nds</theme>
        <emulators>
            <emulator name="drastic">
                <cores>
                    <core incompatible_extensions=".7z">drastic</core>
                </cores>
            </emulator>
        </emulators>
</system>
</systemList>
```

resulsts in the following error:

```
drastic: pcm.c:778: snd_pcm_close: Assertion `pcm' failed.
Aborted

```

**Comment by lolkobr4** [comment]
Downgrading to version 20240213 and tehn upgrading solved this issue.
